name: Keep actions alive
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  keepalive:
    name: Keep actions alive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
