# Test building Squid on several Linux distro / CPU platforms, 32- and 64- bit
# It does not use ccache, as is would be too big to fit in the persistent
#  storage allowed by Github

name: Multi-platform testing

on:
  workflow_dispatch:
    inputs:
      arm:
        description: 'Test on ARM (32-bit)'
        required: false
        default: 'true'
        type: boolean
      arm64:
        description: 'Test on ARM64 (64-bit)'
        required: false
        default: 'true'
        type: boolean
      i386:
        description: 'Test on i386 (32-bit)'
        required: false
        default: 'true'
        type: boolean
      ppc64le:
        description: 'Test on ppc64le (64-bit)'
        required: false
        default: 'true'
        type: boolean
      riscv64:
        description: 'Test on riscv64 (64-bit)'
        required: false
        default: 'true'
        type: boolean
      freebsd:
        description: 'Test on FreeBSD (amd64)'
        required: false
        default: 'true'
        type: boolean

  schedule:
  - cron: "10 3 12 * *" # earlier than multi-platform
#  push:
#    branches: [ github-actions-multiplatform ]

env:
  MAX_CONCURRENT_JOBS: 14
  DOCKER_BUILDFARM_REPO: docker.io/squidcache/buildfarm
  DOCKER_BUILDFARM_TAG: latest
  pjobs: -j`nproc`
  COMPILER_MATRIX_JSON: '[ { "CC": \"gcc\", "CXX": \"g++\" },  { "CC": \"clang\", "CXX": \"clang++\" }]'
  LAYER_MATRIX_JSON: '[ { "name": \"layer-00-default\", "nick": \"default\" }, { "name": \"layer-01-minimal\", "nick": \"minimal\" }, { "name": \"layer-02-maximus\", "nick": \"maximus\" } ]'

concurrency:
  # Cancel ongoing tests in case of push to  branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  gen-matrix:

    runs-on: ubuntu-24.04

    outputs:
      exclusion: ${{ steps.exclusion.outputs.exclusion }}
      os:  ${{ steps.exclusion.outputs.os }}
      compiler: ${{ steps.exclusion.outputs.compiler }}
      layer: ${{ steps.exclusion.outputs.layer }}

    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          repository: kinkie/dockerfiles

      - name: Define exclusion list
        id: exclusion
        run: |
          printf "exclusion=" >> "$GITHUB_OUTPUT"
          make json-exclude-list >> "$GITHUB_OUTPUT"
          printf "os=" >> "$GITHUB_OUTPUT"
          make targets | sed 's/^- /\\"/;s/$/\\", /' | xargs echo | sed 's/^/\[ /;s/,$/\ ]/' >> "$GITHUB_OUTPUT"
          echo "compiler=${{ env.COMPILER_MATRIX_JSON }}" >> "$GITHUB_OUTPUT"
          echo "layer=${{ env.LAYER_MATRIX_JSON }}" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

# job id is the platform : arm / arm64 here

  arm64:
    if: ${{ github.event.inputs.arm64 == 'true' }}
    needs: gen-matrix

    strategy:
      fail-fast: false
      matrix:
        compiler: ${{ fromJSON(needs.gen-matrix.outputs.compiler) }}
        layer: ${{ fromJSON(needs.gen-matrix.outputs.layer) }}
        platform: [arm64]
        os: ${{ fromJSON(needs.gen-matrix.outputs.os) }}
        exclude:  ${{ fromJSON(needs.gen-matrix.outputs.exclusion) }}
    runs-on: ${{ matrix.platform == 'arm' && 'ubuntu-24.04-arm' || matrix.platform == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-22.04' }}

    name: ${{ matrix.platform }}-${{ matrix.os }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}
    env:
      CC: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' && format('ccache {0}', matrix.compiler.CC) || matrix.compiler.CC }}
      CXX: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' && format('ccache {0}', matrix.compiler.CXX) || matrix.compiler.CXX }}

    steps:
      - name: Install QEMU and podman
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static podman

      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          repository: squid-cache/squid
          path: squid

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.17
        if: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' }}
        with:
          verbose: 2 # default 0
          key: ${{ matrix.os }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}

      - name: Run test-builds
        id: test-builds
        run: |
          if docker info >/dev/null 2>&1; then runtime=docker; else runtime=podman; fi
          $runtime run --rm -v $HOME:$HOME -v $PWD:$PWD -w $PWD/squid -u $UID  \
            -e CC -e CXX -e CCACHE_DISABLE \
            --platform linux/${{ matrix.platform == 'arm' && 'arm/v7' || matrix.platform  }} \
            docker.io/squidcache/buildfarm-${{ matrix.os }}:latest \
            ./test-builds.sh --aggressively-use-config-cache --verbose ${{ matrix.layer.name }}

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}
          path: squid/btlayer-*.log

  arm:
    if: ${{ github.event.inputs.arm == 'true' }}
    needs: gen-matrix

    strategy:
      fail-fast: false
      matrix:
        compiler: ${{ fromJSON(needs.gen-matrix.outputs.compiler) }}
        layer: ${{ fromJSON(needs.gen-matrix.outputs.layer) }}
        platform: [arm]
        os: ${{ fromJSON(needs.gen-matrix.outputs.os) }}
        exclude:  ${{ fromJSON(needs.gen-matrix.outputs.exclusion) }}
    runs-on: ${{ matrix.platform == 'arm' && 'ubuntu-24.04-arm' || matrix.platform == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-22.04' }}

    name: ${{ matrix.platform }}-${{ matrix.os }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}
    env:
      CC: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' && format('ccache {0}', matrix.compiler.CC) || matrix.compiler.CC }}
      CXX: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' && format('ccache {0}', matrix.compiler.CXX) || matrix.compiler.CXX }}

    steps:
      - name: Install QEMU and podman
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static podman

      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          repository: squid-cache/squid
          path: squid

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.17
        if: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' }}
        with:
          verbose: 2 # default 0
          key: ${{ matrix.os }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}

      - name: Run test-builds
        id: test-builds
        run: |
          if docker info >/dev/null 2>&1; then runtime=docker; else runtime=podman; fi
          $runtime run --rm -v $HOME:$HOME -v $PWD:$PWD -w $PWD/squid -u $UID  \
            -e CC -e CXX -e CCACHE_DISABLE \
            --platform linux/${{ matrix.platform == 'arm' && 'arm/v7' || matrix.platform  }} \
            docker.io/squidcache/buildfarm-${{ matrix.os }}:latest \
            ./test-builds.sh --aggressively-use-config-cache --verbose ${{ matrix.layer.name }}

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}
          path: squid/btlayer-*.log

  i386:
    if: ${{ github.event.inputs.i386 == 'true' }}
    needs: gen-matrix

    strategy:
      fail-fast: false
      matrix:
        compiler: ${{ fromJSON(needs.gen-matrix.outputs.compiler) }}
        layer: ${{ fromJSON(needs.gen-matrix.outputs.layer) }}
        platform: [i386]
        os: ${{ fromJSON(needs.gen-matrix.outputs.os) }}
        exclude:  ${{ fromJSON(needs.gen-matrix.outputs.exclusion) }}
    runs-on: ${{ matrix.platform == 'arm' && 'ubuntu-24.04-arm' || matrix.platform == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-22.04' }}

    name: ${{ matrix.platform }}-${{ matrix.os }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}
    env:
      CC: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' && format('ccache {0}', matrix.compiler.CC) || matrix.compiler.CC }}
      CXX: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' && format('ccache {0}', matrix.compiler.CXX) || matrix.compiler.CXX }}

    steps:
      - name: Install QEMU and podman
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static podman

      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          repository: squid-cache/squid
          path: squid

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.17
        if: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' }}
        with:
          verbose: 2 # default 0
          key: ${{ matrix.os }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}

      - name: Run test-builds
        id: test-builds
        run: |
          if docker info >/dev/null 2>&1; then runtime=docker; else runtime=podman; fi
          $runtime run --rm -v $HOME:$HOME -v $PWD:$PWD -w $PWD/squid -u $UID  \
            -e CC -e CXX -e CCACHE_DISABLE \
            --platform linux/${{ matrix.platform == 'arm' && 'arm/v7' || matrix.platform  }} \
            docker.io/squidcache/buildfarm-${{ matrix.os }}:latest \
            ./test-builds.sh --aggressively-use-config-cache --verbose ${{ matrix.layer.name }}

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}
          path: squid/btlayer-*.log

  ppc64le:
    if: ${{ github.event.inputs.ppc64le == 'true' }}
    needs: gen-matrix

    strategy:
      fail-fast: false
      matrix:
        compiler: ${{ fromJSON(needs.gen-matrix.outputs.compiler) }}
        layer: ${{ fromJSON(needs.gen-matrix.outputs.layer) }}
        platform: [ppc64le]
        os: ${{ fromJSON(needs.gen-matrix.outputs.os) }}
        exclude:  ${{ fromJSON(needs.gen-matrix.outputs.exclusion) }}
    runs-on: ${{ matrix.platform == 'arm' && 'ubuntu-24.04-arm' || matrix.platform == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-22.04' }}

    name: ${{ matrix.platform }}-${{ matrix.os }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}
    env:
      CC: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' && format('ccache {0}', matrix.compiler.CC) || matrix.compiler.CC }}
      CXX: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' && format('ccache {0}', matrix.compiler.CXX) || matrix.compiler.CXX }}

    steps:
      - name: Install QEMU and podman
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static podman

      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          repository: squid-cache/squid
          path: squid

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.17
        if: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' }}
        with:
          verbose: 2 # default 0
          key: ${{ matrix.os }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}

      - name: Run test-builds
        id: test-builds
        run: |
          if docker info >/dev/null 2>&1; then runtime=docker; else runtime=podman; fi
          $runtime run --rm -v $HOME:$HOME -v $PWD:$PWD -w $PWD/squid -u $UID  \
            -e CC -e CXX -e CCACHE_DISABLE \
            --platform linux/${{ matrix.platform == 'arm' && 'arm/v7' || matrix.platform  }} \
            docker.io/squidcache/buildfarm-${{ matrix.os }}:latest \
            ./test-builds.sh --aggressively-use-config-cache --verbose ${{ matrix.layer.name }}

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}
          path: squid/btlayer-*.log

  riscv64:
    if: ${{ github.event.inputs.riscv64 == 'true' }}
    needs: gen-matrix

    strategy:
      fail-fast: false
      matrix:
        compiler: ${{ fromJSON(needs.gen-matrix.outputs.compiler) }}
        layer: ${{ fromJSON(needs.gen-matrix.outputs.layer) }}
        platform: [riscv64]
        os: ${{ fromJSON(needs.gen-matrix.outputs.os) }}
        exclude:  ${{ fromJSON(needs.gen-matrix.outputs.exclusion) }}
    runs-on: ${{ matrix.platform == 'arm' && 'ubuntu-24.04-arm' || matrix.platform == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-22.04' }}

    name: ${{ matrix.platform }}-${{ matrix.os }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}
    env:
      CC: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' && format('ccache {0}', matrix.compiler.CC) || matrix.compiler.CC }}
      CXX: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' && format('ccache {0}', matrix.compiler.CXX) || matrix.compiler.CXX }}
    steps:
      - name: Install QEMU and podman
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static podman

      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          repository: squid-cache/squid
          path: squid

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.17
        if: ${{ matrix.platform != 'arm' && matrix.platform != 'arm64' && matrix.platform != 'i386' }}
        with:
          verbose: 2 # default 0
          key: ${{ matrix.os }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}

      - name: Run test-builds
        id: test-builds
        run: |
          if docker info >/dev/null 2>&1; then runtime=docker; else runtime=podman; fi
          $runtime run --rm -v $HOME:$HOME -v $PWD:$PWD -w $PWD/squid -u $UID  \
            -e CC -e CXX -e CCACHE_DISABLE \
            --platform linux/${{ matrix.platform == 'arm' && 'arm/v7' || matrix.platform  }} \
            docker.io/squidcache/buildfarm-${{ matrix.os }}:latest \
            ./test-builds.sh --aggressively-use-config-cache --verbose ${{ matrix.layer.name }}

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}
          path: squid/btlayer-*.log



  freebsd-amd64:
    if: ${{ github.event.inputs.freebsd == 'true' }}
    runs-on: ubuntu-24.04 # replicate for -arm

    strategy:
      fail-fast: false
      matrix:
        osversion:
          - "15.0"
          - "14.3"
          - "13.5"

    name: freebsd(${{ matrix.osversion }})

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          repository: squid-cache/squid
          path: squid

      - name: Run test-builds
        id: test-builds
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          release: ${{ matrix.osversion }}
          prepare: |
            export BATCH=yes
            which nproc >/dev/null && echo "MAKE_JOBS_NUMBER?=`nproc --all`" >>/etc/make.conf
            echo "OPTIONS_UNSET=CUPS DEBUG DOCS FONTCONFIG NLS X11" >>/etc/make.conf
            echo "WITHOUT_MODULES=sound ntfs linux" >> /etc/make.conf
            echo "WITHOUT_X11=yes" >>/etc/make.conf
            echo "NO_SENDMAIL=true" >>/etc/make.conf
            echo "IGNORE_OSVERSION=yes" >>/usr/local/etc/pkg.conf

            pkg install -y \
                git-tiny \
                portmaster \
                gmake
            git clone --depth 1 https://git.FreeBSD.org/ports.git /usr/ports
            portmaster -G -H --no-confirm --update-if-newer -t -P -d \
                devel/pkgconf \
                devel/autoconf \
                devel/autoconf-archive \
                devel/automake \
                devel/cppunit \
                devel/libltdl \
                devel/libtool \
                security/nettle \
                textproc/translate-toolkit

          run: |
            export MAKE=gmake
            cd squid
            ./test-builds.sh

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: freebsd-${{ matrix.osversion }}
          path: squid/btlayer-*.log

