name: Test amd64

on:
  workflow_dispatch:
  schedule:
  - cron: "10 3 * * 1"
#  push:
#    branches: [ github-actions-multiplatform ]

jobs:
  amd64:
    uses: ./.github/workflows/platform.yaml
    with: { platform: amd64 }
