name: Test arm

on:
  workflow_dispatch:
  schedule:
  - cron: "10 3 * * 2"
#  push:
#    branches: [ github-actions-multiplatform ]

jobs:
  arm:
    uses: ./.github/workflows/platform.yaml
    with: { platform: arm }
